#!/usr/bin/env python3
"""Plan in rope pixel space with nominal iLQR MPC over a Markov-state MLP world model."""

from __future__ import annotations

import argparse
import json
import os
import re
import time
from pathlib import Path

os.environ.setdefault("MUJOCO_GL", "egl")
os.environ.setdefault("PYOPENGL_PLATFORM", os.environ["MUJOCO_GL"])
os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import h5py
import imageio.v2 as imageio
import mujoco
import numpy as np
import torch
from tqdm.auto import tqdm

from rope.shared.lab_env import LabEnv, TaskState

DEFAULT_TEST_DATASET_PATH = "rope/data/test_data/rope_random_cubic_spline.h5"
DEFAULT_MODEL_DIR = "rope/models/mlpdyn_noshadow_ft"
DEFAULT_OUT_DIR = "rope/plan/ilqr_mpc_mlpdyn"

DEVICE = "auto"
HORIZON = 15
MAX_MPC_STEPS = 50
Q_TERMINAL = 5.0
Q_STAGE = 0.005
R_CONTROL = 0.01
VIDEO_FPS = 20
EPISODE_IDX = None
DISABLE_SHADOWS = True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=Path(DEFAULT_MODEL_DIR))
    parser.add_argument("--checkpoint", type=Path, default=None)
    parser.add_argument("--dataset-path", type=Path, default=Path(DEFAULT_TEST_DATASET_PATH))
    parser.add_argument("--out-dir", type=Path, default=Path(DEFAULT_OUT_DIR))
    parser.add_argument("--device", default=DEVICE)
    parser.add_argument("--episode-idx", type=int, default=EPISODE_IDX)
    parser.add_argument("--horizon", type=int, default=HORIZON)
    parser.add_argument("--max-mpc-steps", type=int, default=MAX_MPC_STEPS)
    parser.add_argument("--frame-batch-size", type=int, default=32)
    parser.add_argument("--video-fps", type=int, default=VIDEO_FPS)
    parser.add_argument(
        "--disable-shadows",
        action="store_true",
        default=DISABLE_SHADOWS,
        help="Disable shadow rendering for frames generated by this script only.",
    )
    parser.add_argument("--goal-tolerance", type=float, default=None)
    parser.add_argument("--q-terminal", type=float, default=Q_TERMINAL)
    parser.add_argument("--q-stage", type=float, default=Q_STAGE)
    parser.add_argument("--r-control", type=float, default=R_CONTROL)
    parser.add_argument("--ilqr-max-iters", type=int, default=15)
    parser.add_argument("--ilqr-tol", type=float, default=1e-4)
    parser.add_argument("--ilqr-regularization", type=float, default=1e-3)
    parser.add_argument("--seed", type=int, default=None)
    return parser.parse_args()


def latest_object_checkpoint(model_dir: Path) -> Path:
    pattern = re.compile(r".*_epoch_(\d+)_object\.ckpt$")
    candidates: list[tuple[int, Path]] = []
    for path in model_dir.glob("*_epoch_*_object.ckpt"):
        match = pattern.match(path.name)
        if match is not None:
            candidates.append((int(match.group(1)), path))
    if not candidates:
        raise FileNotFoundError(f"No object checkpoints matching '*_epoch_N_object.ckpt' found in {model_dir}")
    return max(candidates, key=lambda item: item[0])[1]


def load_config(model_dir: Path) -> dict[str, object]:
    config_path = model_dir / "config.json"
    if not config_path.is_file():
        raise FileNotFoundError(f"Model config not found: {config_path}")
    with config_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def require_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        device_arg = "cuda" if torch.cuda.is_available() else "cpu"
    if device_arg.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but not available.")
    return torch.device(device_arg)


def maybe_cuda_synchronize(device: torch.device) -> None:
    if device.type == "cuda" and torch.cuda.is_available():
        torch.cuda.synchronize(device)


def register_transformers_vit_checkpoint_aliases() -> None:
    """Restore old ViT symbols needed by object checkpoints saved before transformers 5."""

    try:
        import transformers.models.vit.modeling_vit as vit
        from transformers.modeling_outputs import BaseModelOutput
    except Exception:
        return

    if not hasattr(vit, "ViTSelfAttention"):

        class ViTSelfAttention(torch.nn.Module):
            def __init__(self, config):
                super().__init__()
                if config.hidden_size % config.num_attention_heads != 0 and not hasattr(config, "embedding_size"):
                    raise ValueError(
                        f"The hidden size {config.hidden_size} is not a multiple of the number of attention "
                        f"heads {config.num_attention_heads}."
                    )
                self.config = config
                self.num_attention_heads = config.num_attention_heads
                self.attention_head_size = int(config.hidden_size / config.num_attention_heads)
                self.all_head_size = self.num_attention_heads * self.attention_head_size
                self.dropout_prob = config.attention_probs_dropout_prob
                self.scaling = self.attention_head_size**-0.5
                self.is_causal = False
                self.query = torch.nn.Linear(config.hidden_size, self.all_head_size, bias=config.qkv_bias)
                self.key = torch.nn.Linear(config.hidden_size, self.all_head_size, bias=config.qkv_bias)
                self.value = torch.nn.Linear(config.hidden_size, self.all_head_size, bias=config.qkv_bias)

            def forward(self, hidden_states: torch.Tensor, **kwargs):
                batch_size = hidden_states.shape[0]
                new_shape = batch_size, -1, self.num_attention_heads, self.attention_head_size
                key_layer = self.key(hidden_states).view(*new_shape).transpose(1, 2)
                value_layer = self.value(hidden_states).view(*new_shape).transpose(1, 2)
                query_layer = self.query(hidden_states).view(*new_shape).transpose(1, 2)
                attention_interface = vit.ALL_ATTENTION_FUNCTIONS.get_interface(
                    self.config._attn_implementation, vit.eager_attention_forward
                )
                context_layer, attention_probs = attention_interface(
                    self,
                    query_layer,
                    key_layer,
                    value_layer,
                    None,
                    is_causal=self.is_causal,
                    scaling=self.scaling,
                    dropout=0.0 if not self.training else self.dropout_prob,
                    **kwargs,
                )
                context_layer = context_layer.reshape(context_layer.size()[:-2] + (self.all_head_size,))
                return context_layer, attention_probs

        ViTSelfAttention.__module__ = vit.__name__
        vit.ViTSelfAttention = ViTSelfAttention

    if not hasattr(vit, "ViTSelfOutput"):

        class ViTSelfOutput(torch.nn.Module):
            def __init__(self, config):
                super().__init__()
                self.dense = torch.nn.Linear(config.hidden_size, config.hidden_size)
                self.dropout = torch.nn.Dropout(config.hidden_dropout_prob)

            def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor:
                del input_tensor
                hidden_states = self.dense(hidden_states)
                hidden_states = self.dropout(hidden_states)
                return hidden_states

        ViTSelfOutput.__module__ = vit.__name__
        vit.ViTSelfOutput = ViTSelfOutput

    if not hasattr(vit, "ViTIntermediate"):

        class ViTIntermediate(torch.nn.Module):
            def __init__(self, config):
                super().__init__()
                self.dense = torch.nn.Linear(config.hidden_size, config.intermediate_size)
                self.intermediate_act_fn = vit.ACT2FN[config.hidden_act] if isinstance(config.hidden_act, str) else config.hidden_act

            def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
                hidden_states = self.dense(hidden_states)
                hidden_states = self.intermediate_act_fn(hidden_states)
                return hidden_states

        ViTIntermediate.__module__ = vit.__name__
        vit.ViTIntermediate = ViTIntermediate

    if not hasattr(vit, "ViTOutput"):

        class ViTOutput(torch.nn.Module):
            def __init__(self, config):
                super().__init__()
                self.dense = torch.nn.Linear(config.intermediate_size, config.hidden_size)
                self.dropout = torch.nn.Dropout(config.hidden_dropout_prob)

            def forward(self, hidden_states: torch.Tensor, input_tensor: torch.Tensor) -> torch.Tensor:
                hidden_states = self.dense(hidden_states)
                hidden_states = self.dropout(hidden_states)
                hidden_states = hidden_states + input_tensor
                return hidden_states

        ViTOutput.__module__ = vit.__name__
        vit.ViTOutput = ViTOutput

    if not hasattr(vit, "ViTEncoder"):

        class ViTEncoder(torch.nn.Module):
            def __init__(self, config):
                super().__init__()
                self.config = config
                self.layer = torch.nn.ModuleList([vit.ViTLayer(config) for _ in range(config.num_hidden_layers)])
                self.gradient_checkpointing = False

            def forward(self, hidden_states: torch.Tensor, **kwargs):
                for layer_module in self.layer:
                    hidden_states = layer_module(hidden_states, **kwargs)
                return BaseModelOutput(last_hidden_state=hidden_states)

        ViTEncoder.__module__ = vit.__name__
        vit.ViTEncoder = ViTEncoder

    if not getattr(vit.ViTAttention, "_latent_brs_legacy_forward", False):
        new_attention_forward = vit.ViTAttention.forward

        def attention_forward(self, hidden_states: torch.Tensor, *args, **kwargs):
            if hasattr(self, "attention") and hasattr(self, "output"):
                self_attn_output, _ = self.attention(hidden_states, **kwargs)
                return self.output(self_attn_output, hidden_states)
            return new_attention_forward(self, hidden_states, *args, **kwargs)

        attention_forward._latent_brs_legacy_forward = True
        vit.ViTAttention.forward = attention_forward

    if not getattr(vit.ViTLayer, "_latent_brs_legacy_forward", False):
        new_layer_forward = vit.ViTLayer.forward

        def layer_forward(self, hidden_states: torch.Tensor, *args, **kwargs):
            if hasattr(self, "intermediate") and hasattr(self, "output"):
                hidden_states_norm = self.layernorm_before(hidden_states)
                attention_output = self.attention(hidden_states_norm, **kwargs)
                hidden_states = attention_output + hidden_states
                layer_output = self.layernorm_after(hidden_states)
                layer_output = self.intermediate(layer_output)
                return self.output(layer_output, hidden_states)
            return new_layer_forward(self, hidden_states, *args, **kwargs)

        layer_forward._latent_brs_legacy_forward = True
        vit.ViTLayer.forward = layer_forward

    if not getattr(vit.ViTModel, "_latent_brs_legacy_forward", False):
        new_model_forward = vit.ViTModel.forward

        def model_forward(
            self,
            pixel_values: torch.Tensor | None = None,
            bool_masked_pos: torch.BoolTensor | None = None,
            interpolate_pos_encoding: bool | None = None,
            *args,
            **kwargs,
        ):
            if hasattr(self, "encoder"):
                if pixel_values is None:
                    raise ValueError("You have to specify pixel_values")
                expected_dtype = self.embeddings.patch_embeddings.projection.weight.dtype
                if pixel_values.dtype != expected_dtype:
                    pixel_values = pixel_values.to(expected_dtype)
                embedding_output = self.embeddings(
                    pixel_values,
                    bool_masked_pos=bool_masked_pos,
                    interpolate_pos_encoding=interpolate_pos_encoding,
                )
                encoder_outputs = self.encoder(embedding_output)
                sequence_output = self.layernorm(encoder_outputs.last_hidden_state)
                pooled_output = self.pooler(sequence_output) if self.pooler is not None else None
                return vit.BaseModelOutputWithPooling(
                    last_hidden_state=sequence_output,
                    pooler_output=pooled_output,
                )
            return new_model_forward(
                self,
                pixel_values=pixel_values,
                bool_masked_pos=bool_masked_pos,
                interpolate_pos_encoding=interpolate_pos_encoding,
                *args,
                **kwargs,
            )

        model_forward._latent_brs_legacy_forward = True
        vit.ViTModel.forward = model_forward


def load_model(checkpoint_path: Path, device: torch.device) -> torch.nn.Module:
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")
    register_transformers_vit_checkpoint_aliases()
    model = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model = model.to(device)
    model.eval()
    model.requires_grad_(False)
    return model


def save_rgb_image(path: Path, image: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    imageio.imwrite(path, np.ascontiguousarray(image))


def save_rollout_video(frames: list[np.ndarray], out_dir: Path, fps: int) -> Path:
    mp4_path = out_dir / "rollout.mp4"
    gif_path = out_dir / "rollout.gif"
    try:
        imageio.mimwrite(mp4_path, frames, fps=fps, quality=8, macro_block_size=1)
        return mp4_path
    except Exception:
        imageio.mimwrite(gif_path, frames, fps=fps)
        return gif_path


def required_markov_history(markov_deriv: int) -> int:
    if markov_deriv < 0:
        raise ValueError("markov_deriv must be non-negative.")
    return markov_deriv + 1


def build_markov_state(history_emb: torch.Tensor, markov_deriv: int) -> torch.Tensor:
    squeeze = False
    if history_emb.ndim == 2:
        history_emb = history_emb.unsqueeze(0)
        squeeze = True
    context_len = required_markov_history(markov_deriv)
    if history_emb.ndim != 3 or history_emb.shape[1] < context_len:
        raise ValueError(
            f"Expected history_emb with shape [batch, >= {context_len}, dim], got {tuple(history_emb.shape)}."
        )
    deriv_seq = history_emb[:, -context_len:]
    components = [deriv_seq[:, -1]]
    for _ in range(markov_deriv):
        deriv_seq = deriv_seq[:, 1:] - deriv_seq[:, :-1]
        components.append(deriv_seq[:, -1])
    state = torch.cat(components, dim=-1)
    return state[0] if squeeze else state


def preprocess_pixels(
    pixels: np.ndarray | torch.Tensor,
    *,
    img_size: int,
    pixel_mean: torch.Tensor,
    pixel_std: torch.Tensor,
) -> torch.Tensor:
    if isinstance(pixels, np.ndarray):
        tensor = torch.from_numpy(np.ascontiguousarray(pixels))
    else:
        tensor = pixels
    if tensor.ndim == 3:
        tensor = tensor.unsqueeze(0)
    tensor = tensor.permute(0, 3, 1, 2).float().div_(255.0)
    if tuple(tensor.shape[-2:]) != (img_size, img_size):
        tensor = torch.nn.functional.interpolate(
            tensor,
            size=(img_size, img_size),
            mode="bilinear",
            align_corners=False,
        )
    return (tensor - pixel_mean) / pixel_std


@torch.no_grad()
def encode_frames(
    model: torch.nn.Module,
    pixels: torch.Tensor,
    *,
    device: torch.device,
    frame_batch_size: int,
) -> torch.Tensor:
    latents = []
    for start in range(0, pixels.shape[0], frame_batch_size):
        chunk = pixels[start : start + frame_batch_size].to(device)
        output = model.encoder(chunk, interpolate_pos_encoding=True)
        emb = model.projector(output.last_hidden_state[:, 0])
        latents.append(emb)
    return torch.cat(latents, dim=0)


@torch.no_grad()
def encode_single_frame(
    model: torch.nn.Module,
    pixel: np.ndarray,
    *,
    device: torch.device,
    img_size: int,
    pixel_mean: torch.Tensor,
    pixel_std: torch.Tensor,
) -> torch.Tensor:
    batch = preprocess_pixels(pixel, img_size=img_size, pixel_mean=pixel_mean, pixel_std=pixel_std).to(device)
    output = model.encoder(batch, interpolate_pos_encoding=True)
    return model.projector(output.last_hidden_state[:, 0])[0]


def make_markov_state(history: list[torch.Tensor], markov_deriv: int) -> torch.Tensor:
    context_len = required_markov_history(markov_deriv)
    if not history:
        raise ValueError("At least one embedding is required to build the Markov state.")
    history_tensor = torch.stack(history[-context_len:], dim=0)
    if history_tensor.shape[0] < context_len:
        pad = history_tensor[:1].repeat(context_len - history_tensor.shape[0], 1)
        history_tensor = torch.cat((pad, history_tensor), dim=0)
    return build_markov_state(history_tensor, markov_deriv)


def normalized_to_raw_action(action_norm: np.ndarray, action_mean: np.ndarray, action_std: np.ndarray) -> np.ndarray:
    return (action_norm * action_std.reshape(-1) + action_mean.reshape(-1)).astype(np.float32)


def load_dataset_episode(
    dataset_path: Path,
    episode_idx: int,
) -> dict[str, np.ndarray | int | float | str | bool]:
    with h5py.File(dataset_path, "r") as h5:
        ep_len = int(h5["ep_len"][episode_idx])
        ep_offset = int(h5["ep_offset"][episode_idx])
        rows = np.arange(ep_offset, ep_offset + ep_len, dtype=np.int64)
        return {
            "pixels": np.asarray(h5["pixels"][rows], dtype=np.uint8),
            "action": np.asarray(h5["action"][rows], dtype=np.float32),
            "observation": np.asarray(h5["observation"][rows], dtype=np.float32),
            "task_target": np.asarray(h5["task_target"][rows], dtype=np.float32),
            "qpos": np.asarray(h5["qpos"][rows], dtype=np.float32),
            "qvel": np.asarray(h5["qvel"][rows], dtype=np.float32),
            "control": np.asarray(h5["control"][rows], dtype=np.float32),
            "left_attachment_pos": np.asarray(h5["left_attachment_pos"][rows], dtype=np.float32),
            "right_attachment_pos": np.asarray(h5["right_attachment_pos"][rows], dtype=np.float32),
            "rope_length": np.asarray(h5["rope_length"][rows], dtype=np.float32),
            "time": np.asarray(h5["time"][rows], dtype=np.float32),
            "episode_seed": int(h5["episode_seed"][episode_idx]),
            "camera": str(h5.attrs.get("camera", "video_cam")),
            "mode": str(h5.attrs.get("mode", "")),
            "width": int(h5["pixels"].shape[2]),
            "height": int(h5["pixels"].shape[1]),
            "physics_timestep": float(h5.attrs.get("physics_timestep", 1.0 / 500.0)),
            "control_timestep": float(h5.attrs.get("control_timestep", 25.0 / 500.0)),
            "control_decimation": int(h5.attrs.get("control_decimation", 25)),
            "max_episode_steps": int(h5.attrs.get("max_episode_steps", max(ep_len - 1, 1))),
            "goal_tolerance": float(h5.attrs.get("goal_tolerance", 1e-4)),
            "terminated": bool(h5["terminated"][episode_idx]) if "terminated" in h5 else False,
            "truncated": bool(h5["truncated"][episode_idx]) if "truncated" in h5 else False,
        }


def render_rgb_frame(
    renderer: mujoco.Renderer,
    env: LabEnv,
    camera_id: int,
    *,
    disable_shadows: bool = False,
) -> np.ndarray:
    renderer.update_scene(env.data, camera=camera_id)
    if disable_shadows:
        renderer.scene.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
    return np.asarray(renderer.render(), dtype=np.uint8).copy()


def extract_step_info(env: LabEnv, *, elapsed_time: float) -> dict[str, np.ndarray]:
    left_pos = env.data.site_xpos[env.arm1_site_id].copy().astype(np.float32)
    right_pos = env.data.site_xpos[env.arm2_site_id].copy().astype(np.float32)
    rope_length = env.data.ten_length.copy().astype(np.float32)
    task_target = env.task_controller.desired_state.as_array().astype(np.float32)
    qpos = env.data.qpos.copy().astype(np.float32)
    qvel = env.data.qvel.copy().astype(np.float32)
    control = env.data.ctrl.copy().astype(np.float32)
    observation = np.concatenate(
        [
            task_target,
            qpos,
            qvel,
            control,
            left_pos,
            right_pos,
            rope_length,
        ],
        axis=0,
    ).astype(np.float32)
    return {
        "observation": observation,
        "task_target": task_target,
        "qpos": qpos,
        "qvel": qvel,
        "control": control,
        "left_attachment_pos": left_pos,
        "right_attachment_pos": right_pos,
        "rope_length": rope_length,
        "time": np.asarray([elapsed_time], dtype=np.float32),
    }


def reset_env_to_state(
    env: LabEnv,
    renderer: mujoco.Renderer,
    *,
    qpos: np.ndarray,
    qvel: np.ndarray,
    control: np.ndarray,
    task_target: np.ndarray,
    camera_id: int,
    elapsed_time: float,
    disable_shadows: bool,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    env.reset(TaskState.from_array(task_target))
    env.data.qpos[: qpos.shape[0]] = np.asarray(qpos, dtype=np.float64)
    env.data.qvel[: qvel.shape[0]] = np.asarray(qvel, dtype=np.float64)
    env.joint_controller.set_target(np.asarray(control, dtype=np.float64))
    env.task_controller.set_target(TaskState.from_array(task_target))
    env.data.ctrl[:] = np.asarray(control, dtype=np.float64)
    mujoco.mj_forward(env.model, env.data)
    frame = render_rgb_frame(renderer, env, camera_id, disable_shadows=disable_shadows)
    info = extract_step_info(env, elapsed_time=elapsed_time)
    return frame, info


def step_env_with_action(
    env: LabEnv,
    renderer: mujoco.Renderer,
    *,
    action: np.ndarray,
    control_decimation: int,
    camera_id: int,
    elapsed_time: float,
    disable_shadows: bool,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    env.apply_task_delta(np.asarray(action, dtype=np.float64))
    env.step(int(control_decimation))
    frame = render_rgb_frame(renderer, env, camera_id, disable_shadows=disable_shadows)
    info = extract_step_info(env, elapsed_time=elapsed_time)
    return frame, info


class MarkovDynamicsTorch:
    def __init__(self, model: torch.nn.Module, state_dim: int, action_dim: int, device: torch.device) -> None:
        predictor = model.predictor
        if predictor.history_size != 1 or predictor.action_history_size != 1 or predictor.num_preds != 1:
            raise ValueError(
                "This planner expects a one-step Markov MLP dynamics model with "
                "history_size=1, action_history_size=1, and num_preds=1."
            )
        if type(model.action_encoder).__name__ != "Identity":
            raise ValueError("This planner assumes an identity action encoder.")
        if int(predictor.embed_dim) != state_dim:
            raise ValueError(f"Predictor state dim mismatch: expected {state_dim}, got {predictor.embed_dim}.")
        if int(predictor.action_dim) != action_dim:
            raise ValueError(f"Predictor action dim mismatch: expected {action_dim}, got {predictor.action_dim}.")

        self.net = predictor.net.to(device)
        self.state_dim = int(state_dim)
        self.action_dim = int(action_dim)
        self.device = device

    def step(self, x: torch.Tensor, u: torch.Tensor) -> torch.Tensor:
        return self.net(torch.cat((x, u), dim=-1))


class ILQRMPCSolver:
    def __init__(
        self,
        dynamics: MarkovDynamicsTorch,
        *,
        horizon: int,
        q_terminal: float,
        q_stage: float,
        r_control: float,
        max_iters: int,
        tol: float,
        regularization: float,
        device: torch.device,
    ) -> None:
        self.dynamics = dynamics
        self.state_dim = dynamics.state_dim
        self.action_dim = dynamics.action_dim
        self.horizon = int(horizon)
        self.q_terminal = float(q_terminal)
        self.q_stage = float(q_stage)
        self.r_control = float(r_control)
        self.max_iters = int(max_iters)
        self.tol = float(tol)
        self.regularization = float(regularization)
        self.device = device
        self.prev_u_guess = torch.zeros((self.horizon, self.action_dim), dtype=torch.float32, device=device)
        self.eye_x = torch.eye(self.state_dim, dtype=torch.float32, device=device)
        self.eye_u = torch.eye(self.action_dim, dtype=torch.float32, device=device)
        self.line_search_alphas = (1.0, 0.5, 0.25, 0.1, 0.05, 0.01)

    def _make_initial_action_guess(self) -> torch.Tensor:
        if self.horizon <= 1:
            return self.prev_u_guess.clone()
        guess = torch.empty_like(self.prev_u_guess)
        guess[:-1] = self.prev_u_guess[1:]
        guess[-1] = self.prev_u_guess[-1]
        return guess

    def _rollout(self, x0: torch.Tensor, u_seq: torch.Tensor) -> torch.Tensor:
        x_traj = torch.empty((self.horizon + 1, self.state_dim), dtype=x0.dtype, device=self.device)
        x_traj[0] = x0
        x_curr = x0
        for step in range(self.horizon):
            x_curr = self.dynamics.step(x_curr, u_seq[step])
            x_traj[step + 1] = x_curr
        return x_traj

    def _trajectory_cost(self, x_traj: torch.Tensor, u_seq: torch.Tensor, x_goal: torch.Tensor) -> torch.Tensor:
        cost = torch.zeros((), dtype=x_traj.dtype, device=x_traj.device)
        for step in range(self.horizon):
            state_err = x_traj[step] - x_goal
            cost = cost + self.q_stage * torch.dot(state_err, state_err)
            cost = cost + self.r_control * torch.dot(u_seq[step], u_seq[step])
        terminal_err = x_traj[self.horizon] - x_goal
        cost = cost + self.q_terminal * torch.dot(terminal_err, terminal_err)
        return cost

    def _linearize_dynamics(
        self,
        x_traj: torch.Tensor,
        u_seq: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        a_list = []
        b_list = []

        def dyn_cat(inp: torch.Tensor) -> torch.Tensor:
            x = inp[: self.state_dim]
            u = inp[self.state_dim :]
            return self.dynamics.step(x, u)

        for step in range(self.horizon):
            xu = torch.cat((x_traj[step], u_seq[step]), dim=0).detach().requires_grad_(True)
            jac = torch.autograd.functional.jacobian(dyn_cat, xu, vectorize=True)
            a_list.append(jac[:, : self.state_dim].detach())
            b_list.append(jac[:, self.state_dim :].detach())

        return torch.stack(a_list, dim=0), torch.stack(b_list, dim=0)

    def solve(self, x0_np: np.ndarray, x_goal_np: np.ndarray) -> tuple[np.ndarray, np.ndarray, float, int, float]:
        x0 = torch.tensor(x0_np, dtype=torch.float32, device=self.device)
        x_goal = torch.tensor(x_goal_np, dtype=torch.float32, device=self.device)
        u_seq = self._make_initial_action_guess()

        maybe_cuda_synchronize(self.device)
        t0 = time.perf_counter()

        x_traj = self._rollout(x0, u_seq)
        current_cost = float(self._trajectory_cost(x_traj, u_seq, x_goal).item())
        iterations = 0
        reg = self.regularization

        for iteration in range(self.max_iters):
            iterations = iteration + 1
            a_seq, b_seq = self._linearize_dynamics(x_traj, u_seq)
            k_seq = torch.empty((self.horizon, self.action_dim), dtype=torch.float32, device=self.device)
            kk_seq = torch.empty((self.horizon, self.action_dim, self.state_dim), dtype=torch.float32, device=self.device)

            terminal_err = x_traj[self.horizon] - x_goal
            v_x = 2.0 * self.q_terminal * terminal_err
            v_xx = 2.0 * self.q_terminal * self.eye_x
            backward_ok = True

            for step in range(self.horizon - 1, -1, -1):
                x_err = x_traj[step] - x_goal
                u = u_seq[step]
                a = a_seq[step]
                b = b_seq[step]

                l_x = 2.0 * self.q_stage * x_err
                l_u = 2.0 * self.r_control * u
                l_xx = 2.0 * self.q_stage * self.eye_x
                l_uu = 2.0 * self.r_control * self.eye_u

                q_x = l_x + a.T @ v_x
                q_u = l_u + b.T @ v_x
                q_xx = l_xx + a.T @ v_xx @ a
                q_ux = b.T @ v_xx @ a
                q_uu = l_uu + b.T @ v_xx @ b + reg * self.eye_u
                q_uu = 0.5 * (q_uu + q_uu.T)

                try:
                    q_uu_inv = torch.linalg.inv(q_uu)
                except RuntimeError:
                    backward_ok = False
                    break

                k = -q_uu_inv @ q_u
                kk = -q_uu_inv @ q_ux
                k_seq[step] = k
                kk_seq[step] = kk

                v_x = q_x + kk.T @ q_uu @ k + kk.T @ q_u + q_ux.T @ k
                v_xx = q_xx + kk.T @ q_uu @ kk + kk.T @ q_ux + q_ux.T @ kk
                v_xx = 0.5 * (v_xx + v_xx.T)

            if not backward_ok:
                reg = min(reg * 10.0, 1e6)
                continue

            accepted = False
            candidate_best = None
            for alpha in self.line_search_alphas:
                x_new = torch.empty_like(x_traj)
                u_new = torch.empty_like(u_seq)
                x_new[0] = x0
                for step in range(self.horizon):
                    dx = x_new[step] - x_traj[step]
                    u_new[step] = u_seq[step] + alpha * k_seq[step] + kk_seq[step] @ dx
                    x_new[step + 1] = self.dynamics.step(x_new[step], u_new[step])
                new_cost = float(self._trajectory_cost(x_new, u_new, x_goal).item())
                if np.isfinite(new_cost) and new_cost < current_cost:
                    candidate_best = (x_new, u_new, new_cost, alpha)
                    accepted = True
                    break

            if not accepted:
                reg = min(reg * 10.0, 1e6)
                if reg >= 1e6:
                    break
                continue

            x_traj, u_seq, new_cost, alpha = candidate_best
            max_du = float(torch.max(torch.abs(alpha * k_seq)).item())
            cost_improvement = current_cost - new_cost
            current_cost = new_cost
            reg = max(self.regularization, reg * 0.5)

            if cost_improvement <= self.tol or max_du <= self.tol:
                break

        self.prev_u_guess = u_seq.detach().clone()

        maybe_cuda_synchronize(self.device)
        solve_time = time.perf_counter() - t0
        return (
            x_traj.detach().cpu().numpy().astype(np.float64),
            u_seq.detach().cpu().numpy().astype(np.float64),
            solve_time,
            iterations,
            current_cost,
        )


def main() -> None:
    args = parse_args()
    device = require_device(args.device)
    model_dir = args.model_dir.expanduser().resolve()
    dataset_path = args.dataset_path.expanduser().resolve()
    out_root = args.out_dir.expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    config = load_config(model_dir)
    checkpoint_path = (
        args.checkpoint.expanduser().resolve()
        if args.checkpoint is not None
        else latest_object_checkpoint(model_dir).resolve()
    )
    model = load_model(checkpoint_path, device)

    markov_deriv = int(config.get("markov_deriv", 1))
    if markov_deriv < 0:
        raise ValueError(f"Expected non-negative markov_deriv for the MLP model, got {markov_deriv}.")

    img_size = int(config.get("img_size", 224))
    action_dim = int(config.get("action_dim", 3))
    embed_dim = int(config.get("embed_dim", 32))
    markov_state_dim = int(config.get("markov_state_dim", (markov_deriv + 1) * embed_dim))
    frameskip = int(config.get("frameskip", 1))
    if frameskip != 1:
        raise ValueError(f"This rope planner currently expects frameskip=1, got {frameskip}.")

    train_dataset_path = Path(str(config.get("dataset_path", dataset_path))).expanduser().resolve()
    from rope.train.mlpdyn_train import LeWMRopeDataset

    train_stats_dataset = LeWMRopeDataset(
        train_dataset_path,
        markov_deriv=markov_deriv,
        num_preds=1,
        frameskip=frameskip,
        img_size=img_size,
        action_dim=action_dim,
    )
    pixel_mean = torch.tensor([0.485, 0.456, 0.406], dtype=torch.float32).view(1, 3, 1, 1)
    pixel_std = torch.tensor([0.229, 0.224, 0.225], dtype=torch.float32).view(1, 3, 1, 1)
    action_mean = train_stats_dataset.action_mean.astype(np.float32)
    action_std = train_stats_dataset.action_std.astype(np.float32)

    with h5py.File(dataset_path, "r") as h5:
        ep_len = np.asarray(h5["ep_len"][:], dtype=np.int64)

    valid_episodes = np.flatnonzero(ep_len >= 2)
    if valid_episodes.size == 0:
        raise ValueError("Need at least one test trajectory with 2 or more frames.")

    rng = np.random.default_rng(args.seed)
    if args.episode_idx is None:
        episode_idx = int(rng.choice(valid_episodes))
    else:
        episode_idx = int(args.episode_idx)
        if episode_idx < 0 or episode_idx >= ep_len.shape[0]:
            raise ValueError(f"--episode-idx must be in [0, {ep_len.shape[0] - 1}], got {episode_idx}.")
        if ep_len[episode_idx] < 2:
            raise ValueError(f"--episode-idx {episode_idx} must have at least 2 frames, got {ep_len[episode_idx]}.")

    episode = load_dataset_episode(dataset_path, episode_idx)
    episode_seed = int(episode["episode_seed"])
    camera = str(episode["camera"])
    width = int(episode["width"])
    height = int(episode["height"])
    control_decimation = int(episode["control_decimation"])
    dataset_goal_tolerance = float(episode["goal_tolerance"])
    goal_tolerance = float(args.goal_tolerance) if args.goal_tolerance is not None else dataset_goal_tolerance
    dataset_max_episode_steps = int(episode["max_episode_steps"])

    task_target_np = np.asarray(episode["task_target"], dtype=np.float32)
    qpos_np = np.asarray(episode["qpos"], dtype=np.float32)
    qvel_np = np.asarray(episode["qvel"], dtype=np.float32)
    control_np = np.asarray(episode["control"], dtype=np.float32)
    left_attachment_pos_np = np.asarray(episode["left_attachment_pos"], dtype=np.float32)
    right_attachment_pos_np = np.asarray(episode["right_attachment_pos"], dtype=np.float32)
    rope_length_np = np.asarray(episode["rope_length"], dtype=np.float32)
    time_np = np.asarray(episode["time"], dtype=np.float32)
    dataset_pixels_np = np.asarray(episode["pixels"], dtype=np.uint8)

    run_name = f"{int(time.time())}_episode_{episode_idx:05d}"
    out_dir = out_root / run_name
    out_dir.mkdir(parents=True, exist_ok=True)

    env = LabEnv()
    camera_id = env.model.camera(camera).id

    with mujoco.Renderer(env.model, height=height, width=width) as renderer:
        start_frame, start_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[0],
            qvel=qvel_np[0],
            control=control_np[0],
            task_target=task_target_np[0],
            camera_id=camera_id,
            elapsed_time=float(time_np[0, 0]),
            disable_shadows=args.disable_shadows,
        )
        goal_frame, goal_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[-1],
            qvel=qvel_np[-1],
            control=control_np[-1],
            task_target=task_target_np[-1],
            camera_id=camera_id,
            elapsed_time=float(time_np[-1, 0]),
            disable_shadows=args.disable_shadows,
        )
        current_frame, current_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[0],
            qvel=qvel_np[0],
            control=control_np[0],
            task_target=task_target_np[0],
            camera_id=camera_id,
            elapsed_time=float(time_np[0, 0]),
            disable_shadows=args.disable_shadows,
        )

        goal_emb = encode_single_frame(
            model,
            goal_frame,
            device=device,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        current_emb = encode_single_frame(
            model,
            current_frame,
            device=device,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        history_len = required_markov_history(markov_deriv)
        current_history = [current_emb] * history_len
        goal_history = [goal_emb] * history_len
        current_state = make_markov_state(current_history, markov_deriv)
        goal_state = make_markov_state(goal_history, markov_deriv)
        if int(current_state.numel()) != markov_state_dim:
            raise ValueError(f"State dimension mismatch: config says {markov_state_dim}, built {current_state.numel()}.")

        dataset_pixels = preprocess_pixels(
            dataset_pixels_np,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        true_latents = encode_frames(
            model,
            dataset_pixels,
            device=device,
            frame_batch_size=args.frame_batch_size,
        )

        save_rgb_image(out_dir / "start_image.png", start_frame)
        save_rgb_image(out_dir / "goal_image.png", goal_frame)

        dynamics = MarkovDynamicsTorch(model, markov_state_dim, action_dim, device)
        mpc_solver = ILQRMPCSolver(
            dynamics,
            horizon=args.horizon,
            q_terminal=args.q_terminal,
            q_stage=args.q_stage,
            r_control=args.r_control,
            max_iters=args.ilqr_max_iters,
            tol=args.ilqr_tol,
            regularization=args.ilqr_regularization,
            device=device,
        )

        goal_state_np = goal_state.detach().cpu().numpy().astype(np.float64)
        goal_task_target = np.asarray(goal_info["task_target"], dtype=np.float32)
        goal_left_pos = np.asarray(goal_info["left_attachment_pos"], dtype=np.float32)
        goal_right_pos = np.asarray(goal_info["right_attachment_pos"], dtype=np.float32)
        goal_rope_length = np.asarray(goal_info["rope_length"], dtype=np.float32)

        rollout_frames = [current_frame.copy()]
        executed_actions_raw: list[np.ndarray] = []
        executed_actions_norm: list[np.ndarray] = []
        latent_goal_distances = [float(torch.linalg.vector_norm(current_state - goal_state).item())]
        embedding_goal_distances = [float(torch.linalg.vector_norm(current_emb - goal_emb).item())]
        task_target_distances = [float(np.linalg.norm(np.asarray(current_info["task_target"]) - goal_task_target))]
        left_attachment_distances = [float(np.linalg.norm(np.asarray(current_info["left_attachment_pos"]) - goal_left_pos))]
        right_attachment_distances = [float(np.linalg.norm(np.asarray(current_info["right_attachment_pos"]) - goal_right_pos))]
        rope_length_errors = [float(np.linalg.norm(np.asarray(current_info["rope_length"]) - goal_rope_length))]
        solve_times_ms: list[float] = []
        ilqr_iterations: list[int] = []
        ilqr_costs: list[float] = []
        stop_reason = "max_mpc_steps"
        success = bool(task_target_distances[-1] <= goal_tolerance)
        interrupted = False
        pbar = None

        try:
            if not success:
                pbar = tqdm(range(args.max_mpc_steps), desc="MPC Steps")
                for step_idx in pbar:
                    current_state_np = current_state.detach().cpu().numpy().astype(np.float64)
                    _, u_plan, solve_time, n_iters, plan_cost = mpc_solver.solve(current_state_np, goal_state_np)
                    solve_times_ms.append(solve_time * 1000.0)
                    ilqr_iterations.append(int(n_iters))
                    ilqr_costs.append(float(plan_cost))

                    u0_norm = u_plan[0].astype(np.float32)
                    u0_raw = normalized_to_raw_action(u0_norm, action_mean, action_std)

                    current_time = float(current_info["time"][0]) + float(episode["control_timestep"])
                    current_frame, current_info = step_env_with_action(
                        env,
                        renderer,
                        action=u0_raw,
                        control_decimation=control_decimation,
                        camera_id=camera_id,
                        elapsed_time=current_time,
                        disable_shadows=args.disable_shadows,
                    )

                    next_emb = encode_single_frame(
                        model,
                        current_frame,
                        device=device,
                        img_size=img_size,
                        pixel_mean=pixel_mean,
                        pixel_std=pixel_std,
                    )
                    current_history.append(next_emb)
                    current_history = current_history[-history_len:]
                    current_state = make_markov_state(current_history, markov_deriv)
                    current_emb = next_emb

                    executed_actions_norm.append(u0_norm.copy())
                    executed_actions_raw.append(u0_raw.copy())
                    rollout_frames.append(current_frame.copy())
                    latent_goal_distance = float(torch.linalg.vector_norm(current_state - goal_state).item())
                    embedding_goal_distance = float(torch.linalg.vector_norm(current_emb - goal_emb).item())
                    task_target_distance = float(np.linalg.norm(np.asarray(current_info["task_target"]) - goal_task_target))
                    left_attachment_distance = float(np.linalg.norm(np.asarray(current_info["left_attachment_pos"]) - goal_left_pos))
                    right_attachment_distance = float(np.linalg.norm(np.asarray(current_info["right_attachment_pos"]) - goal_right_pos))
                    rope_length_error = float(np.linalg.norm(np.asarray(current_info["rope_length"]) - goal_rope_length))
                    latent_goal_distances.append(latent_goal_distance)
                    embedding_goal_distances.append(embedding_goal_distance)
                    task_target_distances.append(task_target_distance)
                    left_attachment_distances.append(left_attachment_distance)
                    right_attachment_distances.append(right_attachment_distance)
                    rope_length_errors.append(rope_length_error)

                    pbar.set_postfix(
                        solve_ms=f"{solve_times_ms[-1]:.1f}",
                        iters=f"{ilqr_iterations[-1]}",
                        latent_goal=f"{latent_goal_distance:.3f}",
                        task_goal=f"{task_target_distance:.4f}",
                    )

                    if task_target_distance <= goal_tolerance:
                        success = True
                        stop_reason = "goal_tolerance_reached"
                        break
                    if step_idx + 1 >= int(args.max_mpc_steps):
                        stop_reason = "max_mpc_steps"
            else:
                stop_reason = "already_at_goal"
        except KeyboardInterrupt:
            interrupted = True
            stop_reason = "keyboard_interrupt"
        finally:
            if pbar is not None:
                pbar.close()

        final_info = current_info
        metrics = {
            "episode_idx": int(episode_idx),
            "episode_seed": episode_seed,
            "checkpoint": str(checkpoint_path),
            "dataset_path": str(dataset_path),
            "camera": camera,
            "disable_shadows": bool(args.disable_shadows),
            "mode": str(episode["mode"]),
            "img_size": img_size,
            "horizon": int(args.horizon),
            "max_mpc_steps": int(args.max_mpc_steps),
            "goal_tolerance": goal_tolerance,
            "dataset_max_episode_steps": dataset_max_episode_steps,
            "control_decimation": control_decimation,
            "control_timestep": float(episode["control_timestep"]),
            "num_executed_steps": int(len(executed_actions_raw)),
            "success": bool(success),
            "stop_reason": stop_reason,
            "latent_goal_distance_initial": float(latent_goal_distances[0]),
            "latent_goal_distance_final": float(latent_goal_distances[-1]),
            "task_target_distance_initial": float(task_target_distances[0]),
            "task_target_distance_final": float(task_target_distances[-1]),
            "left_attachment_distance_initial": float(left_attachment_distances[0]),
            "left_attachment_distance_final": float(left_attachment_distances[-1]),
            "right_attachment_distance_initial": float(right_attachment_distances[0]),
            "right_attachment_distance_final": float(right_attachment_distances[-1]),
            "rope_length_error_initial": float(rope_length_errors[0]),
            "rope_length_error_final": float(rope_length_errors[-1]),
            "goal_task_target": goal_task_target.tolist(),
            "final_task_target": np.asarray(final_info["task_target"], dtype=np.float32).tolist(),
            "goal_left_attachment_pos": goal_left_pos.tolist(),
            "goal_right_attachment_pos": goal_right_pos.tolist(),
            "final_left_attachment_pos": np.asarray(final_info["left_attachment_pos"], dtype=np.float32).tolist(),
            "final_right_attachment_pos": np.asarray(final_info["right_attachment_pos"], dtype=np.float32).tolist(),
            "goal_rope_length": goal_rope_length.tolist(),
            "final_rope_length": np.asarray(final_info["rope_length"], dtype=np.float32).tolist(),
            "final_qpos": np.asarray(final_info["qpos"], dtype=np.float32).tolist(),
            "final_qvel": np.asarray(final_info["qvel"], dtype=np.float32).tolist(),
            "final_control": np.asarray(final_info["control"], dtype=np.float32).tolist(),
            "solve_times_ms": solve_times_ms,
            "ilqr_iterations": ilqr_iterations,
            "ilqr_costs": ilqr_costs,
            "latent_goal_distances": latent_goal_distances,
            "embedding_goal_distances": embedding_goal_distances,
            "task_target_distances": task_target_distances,
            "left_attachment_distances": left_attachment_distances,
            "right_attachment_distances": right_attachment_distances,
            "rope_length_errors": rope_length_errors,
            "executed_actions_raw": [action.tolist() for action in executed_actions_raw],
            "executed_actions_norm": [action.tolist() for action in executed_actions_norm],
            "dataset_start_pixel_l2": float(np.linalg.norm(start_frame.astype(np.float32) - dataset_pixels_np[0].astype(np.float32))),
            "dataset_goal_pixel_l2": float(np.linalg.norm(goal_frame.astype(np.float32) - dataset_pixels_np[-1].astype(np.float32))),
            "dataset_goal_latent_distance": float(torch.linalg.vector_norm(true_latents[-1] - goal_emb).item()),
        }

    metrics_path = out_dir / "metrics.json"
    with metrics_path.open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=2)

    video_path = str(save_rollout_video(rollout_frames, out_dir, fps=args.video_fps)) if rollout_frames else None

    print(f"Saved to: {out_dir}")
    if video_path is not None:
        print(f"Video: {video_path}")
    print(f"Metrics: {metrics_path}")
    if interrupted:
        print("Interrupted by user; saved partial rollout.")


if __name__ == "__main__":
    main()
