# sls_config.yaml
q_learned: 4.038510 # Update this with the value from conformal_config.json
model_dir: "reacher/models/mlpdyn_ft_1"
error_model_ckpt: "error_model/lightning_logs/version_1/checkpoints/best-error-model-epoch=396.ckpt"
dataset_path: "reacher/data/test_data_50hz/reacher_test.h5"
out_dir: "reacher/plan/sls_mpc_conformal"
device: "auto"
horizon: 25
max_mpc_steps: 120
video_fps: 50
episode_idx: 5  # Use a number (e.g. 5) or null for random
seed: 42
