#!/usr/bin/env python3
"""Plan in rope pixel space with nominal constrained SQP MPC and conformal obstacle constraints."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

os.environ.setdefault("MUJOCO_GL", "egl")
os.environ.setdefault("PYOPENGL_PLATFORM", os.environ["MUJOCO_GL"])
os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import h5py
import imageio.v2 as imageio
import mujoco
import numpy as np
import torch
import torch.nn as nn
from tqdm.auto import tqdm

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rope.shared.lab_env import LabEnv, TaskState
from rope.train.mlpdyn_train import LeWMRopeDataset, build_markov_state, required_markov_history

DEFAULT_TEST_DATASET_PATH = "rope/data/test_data_noshadow.h5"
DEFAULT_MODEL_DIR = "rope/models/mlpdyn_noshadow_ft"
DEFAULT_OUT_DIR = "rope/plan/sqp_mpc_obs"
DEFAULT_OBSTACLE_MODEL_PATH = "rope/plan/obs_net/da270d7d1050f110/model.pt"

DEVICE = "auto"
HORIZON = 30
MAX_MPC_STEPS = 50
Q_TERMINAL = 500.0
Q_STAGE = 0.005
R_CONTROL = 0.01
VIDEO_FPS = 20
EPISODE_IDX = None
DISABLE_SHADOWS = True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-dir", type=Path, default=Path(DEFAULT_MODEL_DIR))
    parser.add_argument("--checkpoint", type=Path, default=None)
    parser.add_argument("--dataset-path", type=Path, default=Path(DEFAULT_TEST_DATASET_PATH))
    parser.add_argument("--out-dir", type=Path, default=Path(DEFAULT_OUT_DIR))
    parser.add_argument("--obstacle-model", type=Path, default=Path(DEFAULT_OBSTACLE_MODEL_PATH))
    parser.add_argument("--device", default=DEVICE)
    parser.add_argument("--episode-idx", type=int, default=EPISODE_IDX)
    parser.add_argument("--horizon", type=int, default=HORIZON)
    parser.add_argument("--max-mpc-steps", type=int, default=MAX_MPC_STEPS)
    parser.add_argument("--frame-batch-size", type=int, default=32)
    parser.add_argument("--video-fps", type=int, default=VIDEO_FPS)
    parser.add_argument(
        "--disable-shadows",
        action="store_true",
        default=DISABLE_SHADOWS,
        help="Disable shadow rendering for frames generated by this script only.",
    )
    parser.add_argument("--goal-tolerance", type=float, default=None)
    parser.add_argument("--q-terminal", type=float, default=Q_TERMINAL)
    parser.add_argument("--q-stage", type=float, default=Q_STAGE)
    parser.add_argument("--r-control", type=float, default=R_CONTROL)
    parser.add_argument("--ilqr-max-iters", type=int, default=15)
    parser.add_argument("--ilqr-tol", type=float, default=1e-4)
    parser.add_argument("--ilqr-regularization", type=float, default=1e-3)
    parser.add_argument("--sqp-max-iters", type=int, default=8)
    parser.add_argument("--sqp-tol", type=float, default=1e-3)
    parser.add_argument("--u-min", type=float, default=-2.0)
    parser.add_argument("--u-max", type=float, default=2.0)
    parser.add_argument("--du-trust", type=float, default=0.5)
    parser.add_argument("--dx-trust", type=float, default=1.0)
    parser.add_argument("--obstacle-margin", type=float, default=0.0)
    parser.add_argument("--obstacle-slack-linear", type=float, default=1_000.0)
    parser.add_argument("--obstacle-slack-quadratic", type=float, default=10_000.0)
    parser.add_argument("--qp-admm-iters", type=int, default=250)
    parser.add_argument("--qp-admm-rho", type=float, default=1.0)
    parser.add_argument("--qp-admm-tol", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=None)
    return parser.parse_args()


def latest_object_checkpoint(model_dir: Path) -> Path:
    pattern = re.compile(r".*_epoch_(\d+)_object\.ckpt$")
    candidates: list[tuple[int, Path]] = []
    for path in model_dir.glob("*_epoch_*_object.ckpt"):
        match = pattern.match(path.name)
        if match is not None:
            candidates.append((int(match.group(1)), path))
    if not candidates:
        raise FileNotFoundError(f"No object checkpoints matching '*_epoch_N_object.ckpt' found in {model_dir}")
    return max(candidates, key=lambda item: item[0])[1]


def load_config(model_dir: Path) -> dict[str, object]:
    config_path = model_dir / "config.json"
    if not config_path.is_file():
        raise FileNotFoundError(f"Model config not found: {config_path}")
    with config_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def require_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        device_arg = "cuda" if torch.cuda.is_available() else "cpu"
    if device_arg.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but not available.")
    return torch.device(device_arg)


def maybe_cuda_synchronize(device: torch.device) -> None:
    if device.type == "cuda" and torch.cuda.is_available():
        torch.cuda.synchronize(device)


def load_model(checkpoint_path: Path, device: torch.device) -> torch.nn.Module:
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")
    model = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model = model.to(device)
    model.eval()
    model.requires_grad_(False)
    return model


def save_rgb_image(path: Path, image: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    imageio.imwrite(path, np.ascontiguousarray(image))


def save_rollout_video(frames: list[np.ndarray], out_dir: Path, fps: int) -> Path:
    mp4_path = out_dir / "rollout.mp4"
    gif_path = out_dir / "rollout.gif"
    try:
        imageio.mimwrite(mp4_path, frames, fps=fps, quality=8, macro_block_size=1)
        return mp4_path
    except Exception:
        imageio.mimwrite(gif_path, frames, fps=fps)
        return gif_path


def preprocess_pixels(
    pixels: np.ndarray | torch.Tensor,
    *,
    img_size: int,
    pixel_mean: torch.Tensor,
    pixel_std: torch.Tensor,
) -> torch.Tensor:
    if isinstance(pixels, np.ndarray):
        tensor = torch.from_numpy(np.ascontiguousarray(pixels))
    else:
        tensor = pixels
    if tensor.ndim == 3:
        tensor = tensor.unsqueeze(0)
    tensor = tensor.permute(0, 3, 1, 2).float().div_(255.0)
    if tuple(tensor.shape[-2:]) != (img_size, img_size):
        tensor = torch.nn.functional.interpolate(
            tensor,
            size=(img_size, img_size),
            mode="bilinear",
            align_corners=False,
        )
    return (tensor - pixel_mean) / pixel_std


@torch.no_grad()
def encode_frames(
    model: torch.nn.Module,
    pixels: torch.Tensor,
    *,
    device: torch.device,
    frame_batch_size: int,
) -> torch.Tensor:
    latents = []
    for start in range(0, pixels.shape[0], frame_batch_size):
        chunk = pixels[start : start + frame_batch_size].to(device)
        output = model.encoder(chunk, interpolate_pos_encoding=True)
        emb = model.projector(output.last_hidden_state[:, 0])
        latents.append(emb)
    return torch.cat(latents, dim=0)


@torch.no_grad()
def encode_single_frame(
    model: torch.nn.Module,
    pixel: np.ndarray,
    *,
    device: torch.device,
    img_size: int,
    pixel_mean: torch.Tensor,
    pixel_std: torch.Tensor,
) -> torch.Tensor:
    batch = preprocess_pixels(pixel, img_size=img_size, pixel_mean=pixel_mean, pixel_std=pixel_std).to(device)
    output = model.encoder(batch, interpolate_pos_encoding=True)
    return model.projector(output.last_hidden_state[:, 0])[0]


def make_markov_state(history: list[torch.Tensor], markov_deriv: int) -> torch.Tensor:
    context_len = required_markov_history(markov_deriv)
    if not history:
        raise ValueError("At least one embedding is required to build the Markov state.")
    history_tensor = torch.stack(history[-context_len:], dim=0)
    if history_tensor.shape[0] < context_len:
        pad = history_tensor[:1].repeat(context_len - history_tensor.shape[0], 1)
        history_tensor = torch.cat((pad, history_tensor), dim=0)
    return build_markov_state(history_tensor, markov_deriv)


def normalized_to_raw_action(action_norm: np.ndarray, action_mean: np.ndarray, action_std: np.ndarray) -> np.ndarray:
    return (action_norm * action_std.reshape(-1) + action_mean.reshape(-1)).astype(np.float32)


def load_dataset_episode(
    dataset_path: Path,
    episode_idx: int,
) -> dict[str, np.ndarray | int | float | str | bool]:
    with h5py.File(dataset_path, "r") as h5:
        ep_len = int(h5["ep_len"][episode_idx])
        ep_offset = int(h5["ep_offset"][episode_idx])
        rows = np.arange(ep_offset, ep_offset + ep_len, dtype=np.int64)
        return {
            "pixels": np.asarray(h5["pixels"][rows], dtype=np.uint8),
            "action": np.asarray(h5["action"][rows], dtype=np.float32),
            "observation": np.asarray(h5["observation"][rows], dtype=np.float32),
            "task_target": np.asarray(h5["task_target"][rows], dtype=np.float32),
            "qpos": np.asarray(h5["qpos"][rows], dtype=np.float32),
            "qvel": np.asarray(h5["qvel"][rows], dtype=np.float32),
            "control": np.asarray(h5["control"][rows], dtype=np.float32),
            "left_attachment_pos": np.asarray(h5["left_attachment_pos"][rows], dtype=np.float32),
            "right_attachment_pos": np.asarray(h5["right_attachment_pos"][rows], dtype=np.float32),
            "rope_length": np.asarray(h5["rope_length"][rows], dtype=np.float32),
            "time": np.asarray(h5["time"][rows], dtype=np.float32),
            "episode_seed": int(h5["episode_seed"][episode_idx]),
            "camera": str(h5.attrs.get("camera", "video_cam")),
            "mode": str(h5.attrs.get("mode", "")),
            "width": int(h5["pixels"].shape[2]),
            "height": int(h5["pixels"].shape[1]),
            "physics_timestep": float(h5.attrs.get("physics_timestep", 1.0 / 500.0)),
            "control_timestep": float(h5.attrs.get("control_timestep", 25.0 / 500.0)),
            "control_decimation": int(h5.attrs.get("control_decimation", 25)),
            "max_episode_steps": int(h5.attrs.get("max_episode_steps", max(ep_len - 1, 1))),
            "goal_tolerance": float(h5.attrs.get("goal_tolerance", 1e-4)),
            "terminated": bool(h5["terminated"][episode_idx]) if "terminated" in h5 else False,
            "truncated": bool(h5["truncated"][episode_idx]) if "truncated" in h5 else False,
        }


def render_rgb_frame(
    renderer: mujoco.Renderer,
    env: LabEnv,
    camera_id: int,
    *,
    disable_shadows: bool = False,
) -> np.ndarray:
    renderer.update_scene(env.data, camera=camera_id)
    if disable_shadows:
        renderer.scene.flags[mujoco.mjtRndFlag.mjRND_SHADOW] = 0
    return np.asarray(renderer.render(), dtype=np.uint8).copy()


def extract_step_info(env: LabEnv, *, elapsed_time: float) -> dict[str, np.ndarray]:
    left_pos = env.data.site_xpos[env.arm1_site_id].copy().astype(np.float32)
    right_pos = env.data.site_xpos[env.arm2_site_id].copy().astype(np.float32)
    rope_length = env.data.ten_length.copy().astype(np.float32)
    task_target = env.task_controller.desired_state.as_array().astype(np.float32)
    qpos = env.data.qpos.copy().astype(np.float32)
    qvel = env.data.qvel.copy().astype(np.float32)
    control = env.data.ctrl.copy().astype(np.float32)
    observation = np.concatenate(
        [
            task_target,
            qpos,
            qvel,
            control,
            left_pos,
            right_pos,
            rope_length,
        ],
        axis=0,
    ).astype(np.float32)
    return {
        "observation": observation,
        "task_target": task_target,
        "qpos": qpos,
        "qvel": qvel,
        "control": control,
        "left_attachment_pos": left_pos,
        "right_attachment_pos": right_pos,
        "rope_length": rope_length,
        "time": np.asarray([elapsed_time], dtype=np.float32),
    }


def reset_env_to_state(
    env: LabEnv,
    renderer: mujoco.Renderer,
    *,
    qpos: np.ndarray,
    qvel: np.ndarray,
    control: np.ndarray,
    task_target: np.ndarray,
    camera_id: int,
    elapsed_time: float,
    disable_shadows: bool,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    env.reset(TaskState.from_array(task_target))
    env.data.qpos[: qpos.shape[0]] = np.asarray(qpos, dtype=np.float64)
    env.data.qvel[: qvel.shape[0]] = np.asarray(qvel, dtype=np.float64)
    env.joint_controller.set_target(np.asarray(control, dtype=np.float64))
    env.task_controller.set_target(TaskState.from_array(task_target))
    env.data.ctrl[:] = np.asarray(control, dtype=np.float64)
    mujoco.mj_forward(env.model, env.data)
    frame = render_rgb_frame(renderer, env, camera_id, disable_shadows=disable_shadows)
    info = extract_step_info(env, elapsed_time=elapsed_time)
    return frame, info


def step_env_with_action(
    env: LabEnv,
    renderer: mujoco.Renderer,
    *,
    action: np.ndarray,
    control_decimation: int,
    camera_id: int,
    elapsed_time: float,
    disable_shadows: bool,
) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    env.apply_task_delta(np.asarray(action, dtype=np.float64))
    env.step(int(control_decimation))
    frame = render_rgb_frame(renderer, env, camera_id, disable_shadows=disable_shadows)
    info = extract_step_info(env, elapsed_time=elapsed_time)
    return frame, info


class ObstacleMLP(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int, depth: int, dropout: float) -> None:
        super().__init__()
        if depth < 1:
            raise ValueError(f"Expected depth >= 1, got {depth}.")
        layers: list[nn.Module] = []
        in_dim = input_dim
        for _ in range(depth - 1):
            layers.append(nn.Linear(in_dim, hidden_dim))
            layers.append(nn.LayerNorm(hidden_dim))
            layers.append(nn.GELU())
            if dropout > 0.0:
                layers.append(nn.Dropout(dropout))
            in_dim = hidden_dim
        layers.append(nn.Linear(in_dim, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).squeeze(-1)


class ConformalObstacleConstraint:
    def __init__(self, artifact_path: Path, device: torch.device) -> None:
        if not artifact_path.is_file():
            raise FileNotFoundError(f"Obstacle model artifact not found: {artifact_path}")
        artifact = torch.load(artifact_path, map_location=device, weights_only=False)
        self.input_dim = int(artifact["input_dim"])
        self.threshold = float(artifact["conformal_safe_score_threshold"])
        self.feature_mean = torch.as_tensor(artifact["feature_mean"], dtype=torch.float32, device=device)
        self.feature_std = torch.as_tensor(artifact["feature_std"], dtype=torch.float32, device=device).clamp_min(1e-6)
        self.model = ObstacleMLP(
            self.input_dim,
            int(artifact["hidden_dim"]),
            int(artifact["depth"]),
            float(artifact["dropout"]),
        ).to(device)
        self.model.load_state_dict(artifact["state_dict"])
        self.model.eval()
        self.model.requires_grad_(False)
        self.device = device

    def score_and_grad(self, x_np: np.ndarray) -> tuple[float, np.ndarray]:
        z = torch.tensor(x_np[: self.input_dim], dtype=torch.float32, device=self.device, requires_grad=True)
        score = self.model((z - self.feature_mean) / self.feature_std)
        grad = torch.autograd.grad(score, z)[0]
        return float(score.detach().cpu().item()), grad.detach().cpu().numpy().astype(np.float64)


class MarkovDynamicsTorch:
    def __init__(self, model: torch.nn.Module, state_dim: int, action_dim: int, device: torch.device) -> None:
        predictor = model.predictor
        if predictor.history_size != 1 or predictor.action_history_size != 1 or predictor.num_preds != 1:
            raise ValueError(
                "This planner expects a one-step Markov MLP dynamics model with "
                "history_size=1, action_history_size=1, and num_preds=1."
            )
        if type(model.action_encoder).__name__ != "Identity":
            raise ValueError("This planner assumes an identity action encoder.")
        if int(predictor.embed_dim) != state_dim:
            raise ValueError(f"Predictor state dim mismatch: expected {state_dim}, got {predictor.embed_dim}.")
        if int(predictor.action_dim) != action_dim:
            raise ValueError(f"Predictor action dim mismatch: expected {action_dim}, got {predictor.action_dim}.")

        self.net = predictor.net.to(device)
        self.state_dim = int(state_dim)
        self.action_dim = int(action_dim)
        self.device = device

    def step(self, x: torch.Tensor, u: torch.Tensor) -> torch.Tensor:
        return self.net(torch.cat((x, u), dim=-1))


class ILQRMPCSolver:
    def __init__(
        self,
        dynamics: MarkovDynamicsTorch,
        *,
        horizon: int,
        q_terminal: float,
        q_stage: float,
        r_control: float,
        max_iters: int,
        tol: float,
        regularization: float,
        device: torch.device,
    ) -> None:
        self.dynamics = dynamics
        self.state_dim = dynamics.state_dim
        self.action_dim = dynamics.action_dim
        self.horizon = int(horizon)
        self.q_terminal = float(q_terminal)
        self.q_stage = float(q_stage)
        self.r_control = float(r_control)
        self.max_iters = int(max_iters)
        self.tol = float(tol)
        self.regularization = float(regularization)
        self.device = device
        self.prev_u_guess = torch.zeros((self.horizon, self.action_dim), dtype=torch.float32, device=device)
        self.eye_x = torch.eye(self.state_dim, dtype=torch.float32, device=device)
        self.eye_u = torch.eye(self.action_dim, dtype=torch.float32, device=device)
        self.line_search_alphas = (1.0, 0.5, 0.25, 0.1, 0.05, 0.01)

    def _make_initial_action_guess(self) -> torch.Tensor:
        if self.horizon <= 1:
            return self.prev_u_guess.clone()
        guess = torch.empty_like(self.prev_u_guess)
        guess[:-1] = self.prev_u_guess[1:]
        guess[-1] = self.prev_u_guess[-1]
        return guess

    def _rollout(self, x0: torch.Tensor, u_seq: torch.Tensor) -> torch.Tensor:
        x_traj = torch.empty((self.horizon + 1, self.state_dim), dtype=x0.dtype, device=self.device)
        x_traj[0] = x0
        x_curr = x0
        for step in range(self.horizon):
            x_curr = self.dynamics.step(x_curr, u_seq[step])
            x_traj[step + 1] = x_curr
        return x_traj

    def _trajectory_cost(self, x_traj: torch.Tensor, u_seq: torch.Tensor, x_goal: torch.Tensor) -> torch.Tensor:
        cost = torch.zeros((), dtype=x_traj.dtype, device=x_traj.device)
        for step in range(self.horizon):
            state_err = x_traj[step] - x_goal
            cost = cost + self.q_stage * torch.dot(state_err, state_err)
            cost = cost + self.r_control * torch.dot(u_seq[step], u_seq[step])
        terminal_err = x_traj[self.horizon] - x_goal
        cost = cost + self.q_terminal * torch.dot(terminal_err, terminal_err)
        return cost

    def _linearize_dynamics(
        self,
        x_traj: torch.Tensor,
        u_seq: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        a_list = []
        b_list = []

        def dyn_cat(inp: torch.Tensor) -> torch.Tensor:
            x = inp[: self.state_dim]
            u = inp[self.state_dim :]
            return self.dynamics.step(x, u)

        for step in range(self.horizon):
            xu = torch.cat((x_traj[step], u_seq[step]), dim=0).detach().requires_grad_(True)
            jac = torch.autograd.functional.jacobian(dyn_cat, xu, vectorize=True)
            a_list.append(jac[:, : self.state_dim].detach())
            b_list.append(jac[:, self.state_dim :].detach())

        return torch.stack(a_list, dim=0), torch.stack(b_list, dim=0)

    def solve(self, x0_np: np.ndarray, x_goal_np: np.ndarray) -> tuple[np.ndarray, np.ndarray, float, int, float]:
        x0 = torch.tensor(x0_np, dtype=torch.float32, device=self.device)
        x_goal = torch.tensor(x_goal_np, dtype=torch.float32, device=self.device)
        u_seq = self._make_initial_action_guess()

        maybe_cuda_synchronize(self.device)
        t0 = time.perf_counter()

        x_traj = self._rollout(x0, u_seq)
        current_cost = float(self._trajectory_cost(x_traj, u_seq, x_goal).item())
        iterations = 0
        reg = self.regularization

        for iteration in range(self.max_iters):
            iterations = iteration + 1
            a_seq, b_seq = self._linearize_dynamics(x_traj, u_seq)
            k_seq = torch.empty((self.horizon, self.action_dim), dtype=torch.float32, device=self.device)
            kk_seq = torch.empty((self.horizon, self.action_dim, self.state_dim), dtype=torch.float32, device=self.device)

            terminal_err = x_traj[self.horizon] - x_goal
            v_x = 2.0 * self.q_terminal * terminal_err
            v_xx = 2.0 * self.q_terminal * self.eye_x
            backward_ok = True

            for step in range(self.horizon - 1, -1, -1):
                x_err = x_traj[step] - x_goal
                u = u_seq[step]
                a = a_seq[step]
                b = b_seq[step]

                l_x = 2.0 * self.q_stage * x_err
                l_u = 2.0 * self.r_control * u
                l_xx = 2.0 * self.q_stage * self.eye_x
                l_uu = 2.0 * self.r_control * self.eye_u

                q_x = l_x + a.T @ v_x
                q_u = l_u + b.T @ v_x
                q_xx = l_xx + a.T @ v_xx @ a
                q_ux = b.T @ v_xx @ a
                q_uu = l_uu + b.T @ v_xx @ b + reg * self.eye_u
                q_uu = 0.5 * (q_uu + q_uu.T)

                try:
                    q_uu_inv = torch.linalg.inv(q_uu)
                except RuntimeError:
                    backward_ok = False
                    break

                k = -q_uu_inv @ q_u
                kk = -q_uu_inv @ q_ux
                k_seq[step] = k
                kk_seq[step] = kk

                v_x = q_x + kk.T @ q_uu @ k + kk.T @ q_u + q_ux.T @ k
                v_xx = q_xx + kk.T @ q_uu @ kk + kk.T @ q_ux + q_ux.T @ kk
                v_xx = 0.5 * (v_xx + v_xx.T)

            if not backward_ok:
                reg = min(reg * 10.0, 1e6)
                continue

            accepted = False
            candidate_best = None
            for alpha in self.line_search_alphas:
                x_new = torch.empty_like(x_traj)
                u_new = torch.empty_like(u_seq)
                x_new[0] = x0
                for step in range(self.horizon):
                    dx = x_new[step] - x_traj[step]
                    u_new[step] = u_seq[step] + alpha * k_seq[step] + kk_seq[step] @ dx
                    x_new[step + 1] = self.dynamics.step(x_new[step], u_new[step])
                new_cost = float(self._trajectory_cost(x_new, u_new, x_goal).item())
                if np.isfinite(new_cost) and new_cost < current_cost:
                    candidate_best = (x_new, u_new, new_cost, alpha)
                    accepted = True
                    break

            if not accepted:
                reg = min(reg * 10.0, 1e6)
                if reg >= 1e6:
                    break
                continue

            x_traj, u_seq, new_cost, alpha = candidate_best
            max_du = float(torch.max(torch.abs(alpha * k_seq)).item())
            cost_improvement = current_cost - new_cost
            current_cost = new_cost
            reg = max(self.regularization, reg * 0.5)

            if cost_improvement <= self.tol or max_du <= self.tol:
                break

        self.prev_u_guess = u_seq.detach().clone()

        maybe_cuda_synchronize(self.device)
        solve_time = time.perf_counter() - t0
        return (
            x_traj.detach().cpu().numpy().astype(np.float64),
            u_seq.detach().cpu().numpy().astype(np.float64),
            solve_time,
            iterations,
            current_cost,
        )


class SQPObstacleMPCSolver:
    def __init__(
        self,
        dynamics: MarkovDynamicsTorch,
        obstacle: ConformalObstacleConstraint,
        *,
        horizon: int,
        q_terminal: float,
        q_stage: float,
        r_control: float,
        max_iters: int,
        tol: float,
        u_min: float,
        u_max: float,
        dx_trust: float,
        du_trust: float,
        obstacle_margin: float,
        obstacle_slack_linear: float,
        obstacle_slack_quadratic: float,
        qp_admm_iters: int,
        qp_admm_rho: float,
        qp_admm_tol: float,
        device: torch.device,
    ) -> None:
        self.dynamics = dynamics
        self.obstacle = obstacle
        self.state_dim = dynamics.state_dim
        self.action_dim = dynamics.action_dim
        self.horizon = int(horizon)
        self.q_terminal = float(q_terminal)
        self.q_stage = float(q_stage)
        self.r_control = float(r_control)
        self.max_iters = int(max_iters)
        self.tol = float(tol)
        self.u_min = float(u_min)
        self.u_max = float(u_max)
        self.dx_trust = float(dx_trust)
        self.du_trust = float(du_trust)
        self.obstacle_margin = float(obstacle_margin)
        self.obstacle_slack_linear = float(obstacle_slack_linear)
        self.obstacle_slack_quadratic = float(obstacle_slack_quadratic)
        self.qp_admm_iters = int(qp_admm_iters)
        self.qp_admm_rho = float(qp_admm_rho)
        self.qp_admm_tol = float(qp_admm_tol)
        self.device = device
        self.prev_u_guess = torch.zeros((self.horizon, self.action_dim), dtype=torch.float32, device=device)

    def _make_initial_action_guess(self) -> torch.Tensor:
        if self.horizon <= 1:
            return self.prev_u_guess.clone()
        guess = torch.empty_like(self.prev_u_guess)
        guess[:-1] = self.prev_u_guess[1:]
        guess[-1] = self.prev_u_guess[-1]
        return guess.clamp_(self.u_min, self.u_max)

    def _rollout(self, x0: torch.Tensor, u_seq: torch.Tensor) -> torch.Tensor:
        x_traj = torch.empty((self.horizon + 1, self.state_dim), dtype=x0.dtype, device=self.device)
        x_traj[0] = x0
        x_curr = x0
        for step in range(self.horizon):
            x_curr = self.dynamics.step(x_curr, u_seq[step])
            x_traj[step + 1] = x_curr
        return x_traj

    def _trajectory_cost(self, x_traj: torch.Tensor, u_seq: torch.Tensor, x_goal: torch.Tensor) -> torch.Tensor:
        cost = torch.zeros((), dtype=x_traj.dtype, device=x_traj.device)
        for step in range(self.horizon):
            state_err = x_traj[step] - x_goal
            cost = cost + self.q_stage * torch.dot(state_err, state_err)
            cost = cost + self.r_control * torch.dot(u_seq[step], u_seq[step])
        terminal_err = x_traj[self.horizon] - x_goal
        return cost + self.q_terminal * torch.dot(terminal_err, terminal_err)

    def _linearize_dynamics(self, x_traj: torch.Tensor, u_seq: torch.Tensor) -> tuple[np.ndarray, np.ndarray]:
        a_list = []
        b_list = []

        def dyn_cat(inp: torch.Tensor) -> torch.Tensor:
            x = inp[: self.state_dim]
            u = inp[self.state_dim :]
            return self.dynamics.step(x, u)

        for step in range(self.horizon):
            xu = torch.cat((x_traj[step], u_seq[step]), dim=0).detach().requires_grad_(True)
            jac = torch.autograd.functional.jacobian(dyn_cat, xu, vectorize=True)
            a_list.append(jac[:, : self.state_dim].detach().cpu().numpy().astype(np.float64))
            b_list.append(jac[:, self.state_dim :].detach().cpu().numpy().astype(np.float64))
        return np.stack(a_list, axis=0), np.stack(b_list, axis=0)

    def _solve_linearized_qp(
        self,
        x_bar: np.ndarray,
        u_bar: np.ndarray,
        a_seq: np.ndarray,
        b_seq: np.ndarray,
        x_goal: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, bool]:
        nx, nu, n_h = self.state_dim, self.action_dim, self.horizon
        n_du = n_h * nu
        total = n_du + n_h

        def du_slice(t: int) -> slice:
            return slice(t * nu, (t + 1) * nu)

        def slack_index(t: int) -> int:
            return n_du + (t - 1)

        state_map = np.zeros((n_h, nx, n_du), dtype=np.float64)
        prev = np.zeros((nx, n_du), dtype=np.float64)
        for t in range(n_h):
            curr = a_seq[t] @ prev
            curr[:, du_slice(t)] += b_seq[t]
            state_map[t] = curr
            prev = curr

        h = np.zeros((total, total), dtype=np.float64)
        g = np.zeros(total, dtype=np.float64)
        for t in range(1, n_h + 1):
            weight = self.q_terminal if t == n_h else self.q_stage
            s_t = state_map[t - 1]
            h[:n_du, :n_du] += 2.0 * weight * (s_t.T @ s_t)
            g[:n_du] += 2.0 * weight * (s_t.T @ (x_bar[t] - x_goal))
        for t in range(n_h):
            sl = du_slice(t)
            h[sl, sl] += 2.0 * self.r_control * np.eye(nu)
            g[sl] += 2.0 * self.r_control * u_bar[t]
        for t in range(1, n_h + 1):
            idx = slack_index(t)
            h[idx, idx] = 2.0 * self.obstacle_slack_quadratic
            g[idx] = self.obstacle_slack_linear

        a_rows = []
        lower = []
        upper = []
        for t in range(1, n_h + 1):
            score, grad_z = self.obstacle.score_and_grad(x_bar[t])
            row = np.zeros(total, dtype=np.float64)
            row[:n_du] = grad_z @ state_map[t - 1, : self.obstacle.input_dim]
            row[slack_index(t)] = 1.0
            a_rows.append(row)
            lower.append(self.obstacle.threshold + self.obstacle_margin - score)
            upper.append(np.inf)

        for t in range(n_h):
            for j in range(nu):
                row = np.zeros(total, dtype=np.float64)
                idx = du_slice(t).start + j
                row[idx] = 1.0
                a_rows.append(row)
                lower.append(max(self.u_min - u_bar[t, j], -self.du_trust))
                upper.append(min(self.u_max - u_bar[t, j], self.du_trust))
        for t in range(1, n_h + 1):
            row = np.zeros(total, dtype=np.float64)
            row[slack_index(t)] = 1.0
            a_rows.append(row)
            lower.append(0.0)
            upper.append(np.inf)
        for t in range(1, n_h + 1):
            for j in range(nx):
                row = np.zeros(total, dtype=np.float64)
                row[:n_du] = state_map[t - 1, j]
                a_rows.append(row)
                lower.append(-self.dx_trust)
                upper.append(self.dx_trust)

        a_mat = np.stack(a_rows, axis=0)
        lower_arr = np.asarray(lower, dtype=np.float64)
        upper_arr = np.asarray(upper, dtype=np.float64)
        rho = self.qp_admm_rho
        lhs = h + rho * (a_mat.T @ a_mat) + 1e-8 * np.eye(total)
        try:
            chol = np.linalg.cholesky(lhs)
        except np.linalg.LinAlgError:
            lhs = lhs + 1e-5 * np.eye(total)
            chol = np.linalg.cholesky(lhs)

        def solve_lhs(rhs: np.ndarray) -> np.ndarray:
            return np.linalg.solve(chol.T, np.linalg.solve(chol, rhs))

        y = np.zeros(total, dtype=np.float64)
        projection = np.clip(a_mat @ y, lower_arr, upper_arr)
        dual = np.zeros_like(projection)
        converged = False
        for _ in range(self.qp_admm_iters):
            y = solve_lhs(-g + rho * a_mat.T @ (projection - dual))
            ay = a_mat @ y
            prev_projection = projection
            projection = np.minimum(np.maximum(ay + dual, lower_arr), upper_arr)
            dual = dual + ay - projection
            primal_res = float(np.linalg.norm(ay - projection, ord=np.inf))
            dual_res = float(rho * np.linalg.norm(a_mat.T @ (projection - prev_projection), ord=np.inf))
            if primal_res <= self.qp_admm_tol and dual_res <= self.qp_admm_tol:
                converged = True
                break

        du_flat = y[:n_du].copy()
        for t in range(n_h):
            sl = du_slice(t)
            du_flat[sl] = np.clip(
                du_flat[sl],
                np.maximum(self.u_min - u_bar[t], -self.du_trust),
                np.minimum(self.u_max - u_bar[t], self.du_trust),
            )
        slack = np.maximum(y[n_du:], 0.0)
        dx_flat = state_map.reshape(n_h * nx, n_du) @ du_flat
        dx = np.zeros((n_h + 1, nx), dtype=np.float64)
        du = np.zeros((n_h, nu), dtype=np.float64)
        for t in range(1, n_h + 1):
            dx[t] = dx_flat[(t - 1) * nx : t * nx]
        for t in range(n_h):
            du[t] = du_flat[du_slice(t)]
        return dx, du, slack, converged

    def solve(self, x0_np: np.ndarray, x_goal_np: np.ndarray) -> tuple[np.ndarray, np.ndarray, float, int, float, float, bool]:
        x0 = torch.tensor(x0_np, dtype=torch.float32, device=self.device)
        x_goal = torch.tensor(x_goal_np, dtype=torch.float32, device=self.device)
        u_seq = self._make_initial_action_guess()

        maybe_cuda_synchronize(self.device)
        t0 = time.perf_counter()
        accepted_any = False
        max_slack = 0.0

        x_traj = self._rollout(x0, u_seq)
        current_cost = float(self._trajectory_cost(x_traj, u_seq, x_goal).item())
        iterations = 0

        for iteration in range(self.max_iters):
            iterations = iteration + 1
            a_seq, b_seq = self._linearize_dynamics(x_traj, u_seq)
            x_bar = x_traj.detach().cpu().numpy().astype(np.float64)
            u_bar = u_seq.detach().cpu().numpy().astype(np.float64)
            dx, du, slack, qp_ok = self._solve_linearized_qp(x_bar, u_bar, a_seq, b_seq, x_goal_np)
            max_slack = float(np.max(slack)) if slack.size else 0.0
            if not qp_ok and not np.all(np.isfinite(du)):
                break

            step_norm = float(max(np.max(np.abs(dx)), np.max(np.abs(du))))
            accepted = False
            candidate_best = None
            for alpha in (1.0, 0.5, 0.25, 0.1):
                u_candidate_np = np.clip(u_bar + alpha * du, self.u_min, self.u_max)
                u_candidate = torch.tensor(u_candidate_np, dtype=torch.float32, device=self.device)
                x_candidate = self._rollout(x0, u_candidate)
                candidate_cost = float(self._trajectory_cost(x_candidate, u_candidate, x_goal).item())
                if not np.isfinite(candidate_cost):
                    continue
                if candidate_best is None or candidate_cost < candidate_best[2]:
                    candidate_best = (u_candidate, x_candidate, candidate_cost)
                if candidate_cost <= current_cost + 1e-6:
                    break

            if candidate_best is None:
                break
            u_seq, x_traj, candidate_cost = candidate_best
            accepted = candidate_cost <= current_cost + 1e-6
            current_cost = candidate_cost
            accepted_any = accepted_any or accepted
            if step_norm <= self.tol:
                break

        self.prev_u_guess = u_seq.detach().clone()
        maybe_cuda_synchronize(self.device)
        solve_time = time.perf_counter() - t0
        return (
            x_traj.detach().cpu().numpy().astype(np.float64),
            u_seq.detach().cpu().numpy().astype(np.float64),
            solve_time,
            iterations,
            current_cost,
            max_slack,
            accepted_any,
        )


def main() -> None:
    args = parse_args()
    device = require_device(args.device)
    model_dir = args.model_dir.expanduser().resolve()
    dataset_path = args.dataset_path.expanduser().resolve()
    out_root = args.out_dir.expanduser().resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    config = load_config(model_dir)
    checkpoint_path = (
        args.checkpoint.expanduser().resolve()
        if args.checkpoint is not None
        else latest_object_checkpoint(model_dir).resolve()
    )
    model = load_model(checkpoint_path, device)

    markov_deriv = int(config.get("markov_deriv", 1))
    if markov_deriv < 0:
        raise ValueError(f"Expected non-negative markov_deriv for the MLP model, got {markov_deriv}.")

    img_size = int(config.get("img_size", 224))
    action_dim = int(config.get("action_dim", 3))
    embed_dim = int(config.get("embed_dim", 32))
    markov_state_dim = int(config.get("markov_state_dim", (markov_deriv + 1) * embed_dim))
    frameskip = int(config.get("frameskip", 1))
    if frameskip != 1:
        raise ValueError(f"This rope planner currently expects frameskip=1, got {frameskip}.")

    train_dataset_path = Path(str(config.get("dataset_path", dataset_path))).expanduser().resolve()
    train_stats_dataset = LeWMRopeDataset(
        train_dataset_path,
        markov_deriv=markov_deriv,
        num_preds=1,
        frameskip=frameskip,
        img_size=img_size,
        action_dim=action_dim,
    )
    pixel_mean = torch.tensor([0.485, 0.456, 0.406], dtype=torch.float32).view(1, 3, 1, 1)
    pixel_std = torch.tensor([0.229, 0.224, 0.225], dtype=torch.float32).view(1, 3, 1, 1)
    action_mean = train_stats_dataset.action_mean.astype(np.float32)
    action_std = train_stats_dataset.action_std.astype(np.float32)

    with h5py.File(dataset_path, "r") as h5:
        ep_len = np.asarray(h5["ep_len"][:], dtype=np.int64)

    valid_episodes = np.flatnonzero(ep_len >= 2)
    if valid_episodes.size == 0:
        raise ValueError("Need at least one test trajectory with 2 or more frames.")

    rng = np.random.default_rng(args.seed)
    if args.episode_idx is None:
        episode_idx = int(rng.choice(valid_episodes))
    else:
        episode_idx = int(args.episode_idx)
        if episode_idx < 0 or episode_idx >= ep_len.shape[0]:
            raise ValueError(f"--episode-idx must be in [0, {ep_len.shape[0] - 1}], got {episode_idx}.")
        if ep_len[episode_idx] < 2:
            raise ValueError(f"--episode-idx {episode_idx} must have at least 2 frames, got {ep_len[episode_idx]}.")

    episode = load_dataset_episode(dataset_path, episode_idx)
    episode_seed = int(episode["episode_seed"])
    camera = str(episode["camera"])
    width = int(episode["width"])
    height = int(episode["height"])
    control_decimation = int(episode["control_decimation"])
    dataset_goal_tolerance = float(episode["goal_tolerance"])
    goal_tolerance = float(args.goal_tolerance) if args.goal_tolerance is not None else dataset_goal_tolerance
    dataset_max_episode_steps = int(episode["max_episode_steps"])

    task_target_np = np.asarray(episode["task_target"], dtype=np.float32)
    qpos_np = np.asarray(episode["qpos"], dtype=np.float32)
    qvel_np = np.asarray(episode["qvel"], dtype=np.float32)
    control_np = np.asarray(episode["control"], dtype=np.float32)
    left_attachment_pos_np = np.asarray(episode["left_attachment_pos"], dtype=np.float32)
    right_attachment_pos_np = np.asarray(episode["right_attachment_pos"], dtype=np.float32)
    rope_length_np = np.asarray(episode["rope_length"], dtype=np.float32)
    time_np = np.asarray(episode["time"], dtype=np.float32)
    dataset_pixels_np = np.asarray(episode["pixels"], dtype=np.uint8)

    run_name = f"{int(time.time())}_episode_{episode_idx:05d}"
    out_dir = out_root / run_name
    out_dir.mkdir(parents=True, exist_ok=True)

    env = LabEnv()
    camera_id = env.model.camera(camera).id

    with mujoco.Renderer(env.model, height=height, width=width) as renderer:
        start_frame, start_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[0],
            qvel=qvel_np[0],
            control=control_np[0],
            task_target=task_target_np[0],
            camera_id=camera_id,
            elapsed_time=float(time_np[0, 0]),
            disable_shadows=args.disable_shadows,
        )
        goal_frame, goal_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[-1],
            qvel=qvel_np[-1],
            control=control_np[-1],
            task_target=task_target_np[-1],
            camera_id=camera_id,
            elapsed_time=float(time_np[-1, 0]),
            disable_shadows=args.disable_shadows,
        )
        current_frame, current_info = reset_env_to_state(
            env,
            renderer,
            qpos=qpos_np[0],
            qvel=qvel_np[0],
            control=control_np[0],
            task_target=task_target_np[0],
            camera_id=camera_id,
            elapsed_time=float(time_np[0, 0]),
            disable_shadows=args.disable_shadows,
        )

        goal_emb = encode_single_frame(
            model,
            goal_frame,
            device=device,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        current_emb = encode_single_frame(
            model,
            current_frame,
            device=device,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        history_len = required_markov_history(markov_deriv)
        current_history = [current_emb] * history_len
        goal_history = [goal_emb] * history_len
        current_state = make_markov_state(current_history, markov_deriv)
        goal_state = make_markov_state(goal_history, markov_deriv)
        if int(current_state.numel()) != markov_state_dim:
            raise ValueError(f"State dimension mismatch: config says {markov_state_dim}, built {current_state.numel()}.")

        dataset_pixels = preprocess_pixels(
            dataset_pixels_np,
            img_size=img_size,
            pixel_mean=pixel_mean,
            pixel_std=pixel_std,
        )
        true_latents = encode_frames(
            model,
            dataset_pixels,
            device=device,
            frame_batch_size=args.frame_batch_size,
        )

        save_rgb_image(out_dir / "start_image.png", start_frame)
        save_rgb_image(out_dir / "goal_image.png", goal_frame)

        dynamics = MarkovDynamicsTorch(model, markov_state_dim, action_dim, device)
        obstacle_constraint = ConformalObstacleConstraint(args.obstacle_model.expanduser().resolve(), device)
        if obstacle_constraint.input_dim > markov_state_dim:
            raise ValueError(
                f"Obstacle input dim {obstacle_constraint.input_dim} is larger than state dim {markov_state_dim}."
            )
        mpc_solver = SQPObstacleMPCSolver(
            dynamics,
            obstacle_constraint,
            horizon=args.horizon,
            q_terminal=args.q_terminal,
            q_stage=args.q_stage,
            r_control=args.r_control,
            max_iters=args.sqp_max_iters,
            tol=args.sqp_tol,
            u_min=args.u_min,
            u_max=args.u_max,
            dx_trust=args.dx_trust,
            du_trust=args.du_trust,
            obstacle_margin=args.obstacle_margin,
            obstacle_slack_linear=args.obstacle_slack_linear,
            obstacle_slack_quadratic=args.obstacle_slack_quadratic,
            qp_admm_iters=args.qp_admm_iters,
            qp_admm_rho=args.qp_admm_rho,
            qp_admm_tol=args.qp_admm_tol,
            device=device,
        )

        goal_state_np = goal_state.detach().cpu().numpy().astype(np.float64)
        goal_task_target = np.asarray(goal_info["task_target"], dtype=np.float32)
        goal_left_pos = np.asarray(goal_info["left_attachment_pos"], dtype=np.float32)
        goal_right_pos = np.asarray(goal_info["right_attachment_pos"], dtype=np.float32)
        goal_rope_length = np.asarray(goal_info["rope_length"], dtype=np.float32)

        rollout_frames = [current_frame.copy()]
        executed_actions_raw: list[np.ndarray] = []
        executed_actions_norm: list[np.ndarray] = []
        latent_goal_distances = [float(torch.linalg.vector_norm(current_state - goal_state).item())]
        embedding_goal_distances = [float(torch.linalg.vector_norm(current_emb - goal_emb).item())]
        task_target_distances = [float(np.linalg.norm(np.asarray(current_info["task_target"]) - goal_task_target))]
        left_attachment_distances = [float(np.linalg.norm(np.asarray(current_info["left_attachment_pos"]) - goal_left_pos))]
        right_attachment_distances = [float(np.linalg.norm(np.asarray(current_info["right_attachment_pos"]) - goal_right_pos))]
        rope_length_errors = [float(np.linalg.norm(np.asarray(current_info["rope_length"]) - goal_rope_length))]
        solve_times_ms: list[float] = []
        sqp_iterations: list[int] = []
        sqp_costs: list[float] = []
        obstacle_slacks: list[float] = []
        solver_accepted: list[bool] = []
        stop_reason = "max_mpc_steps"
        success = bool(task_target_distances[-1] <= goal_tolerance)
        interrupted = False
        pbar = None

        try:
            if not success:
                pbar = tqdm(range(args.max_mpc_steps), desc="MPC Steps")
                for step_idx in pbar:
                    current_state_np = current_state.detach().cpu().numpy().astype(np.float64)
                    _, u_plan, solve_time, n_iters, plan_cost, max_slack, accepted = mpc_solver.solve(
                        current_state_np,
                        goal_state_np,
                    )
                    solve_times_ms.append(solve_time * 1000.0)
                    sqp_iterations.append(int(n_iters))
                    sqp_costs.append(float(plan_cost))
                    obstacle_slacks.append(float(max_slack))
                    solver_accepted.append(bool(accepted))

                    u0_norm = u_plan[0].astype(np.float32)
                    u0_raw = normalized_to_raw_action(u0_norm, action_mean, action_std)

                    current_time = float(current_info["time"][0]) + float(episode["control_timestep"])
                    current_frame, current_info = step_env_with_action(
                        env,
                        renderer,
                        action=u0_raw,
                        control_decimation=control_decimation,
                        camera_id=camera_id,
                        elapsed_time=current_time,
                        disable_shadows=args.disable_shadows,
                    )

                    next_emb = encode_single_frame(
                        model,
                        current_frame,
                        device=device,
                        img_size=img_size,
                        pixel_mean=pixel_mean,
                        pixel_std=pixel_std,
                    )
                    current_history.append(next_emb)
                    current_history = current_history[-history_len:]
                    current_state = make_markov_state(current_history, markov_deriv)
                    current_emb = next_emb

                    executed_actions_norm.append(u0_norm.copy())
                    executed_actions_raw.append(u0_raw.copy())
                    rollout_frames.append(current_frame.copy())
                    latent_goal_distance = float(torch.linalg.vector_norm(current_state - goal_state).item())
                    embedding_goal_distance = float(torch.linalg.vector_norm(current_emb - goal_emb).item())
                    task_target_distance = float(np.linalg.norm(np.asarray(current_info["task_target"]) - goal_task_target))
                    left_attachment_distance = float(np.linalg.norm(np.asarray(current_info["left_attachment_pos"]) - goal_left_pos))
                    right_attachment_distance = float(np.linalg.norm(np.asarray(current_info["right_attachment_pos"]) - goal_right_pos))
                    rope_length_error = float(np.linalg.norm(np.asarray(current_info["rope_length"]) - goal_rope_length))
                    latent_goal_distances.append(latent_goal_distance)
                    embedding_goal_distances.append(embedding_goal_distance)
                    task_target_distances.append(task_target_distance)
                    left_attachment_distances.append(left_attachment_distance)
                    right_attachment_distances.append(right_attachment_distance)
                    rope_length_errors.append(rope_length_error)

                    pbar.set_postfix(
                        solve_ms=f"{solve_times_ms[-1]:.1f}",
                        iters=f"{sqp_iterations[-1]}",
                        slack=f"{obstacle_slacks[-1]:.3g}",
                        latent_goal=f"{latent_goal_distance:.3f}",
                        task_goal=f"{task_target_distance:.4f}",
                    )

                    if task_target_distance <= goal_tolerance:
                        success = True
                        stop_reason = "goal_tolerance_reached"
                        break
                    if step_idx + 1 >= int(args.max_mpc_steps):
                        stop_reason = "max_mpc_steps"
            else:
                stop_reason = "already_at_goal"
        except KeyboardInterrupt:
            interrupted = True
            stop_reason = "keyboard_interrupt"
        finally:
            if pbar is not None:
                pbar.close()

        final_info = current_info
        metrics = {
            "episode_idx": int(episode_idx),
            "episode_seed": episode_seed,
            "checkpoint": str(checkpoint_path),
            "dataset_path": str(dataset_path),
            "camera": camera,
            "disable_shadows": bool(args.disable_shadows),
            "mode": str(episode["mode"]),
            "img_size": img_size,
            "horizon": int(args.horizon),
            "solver": "nominal_sqp_conformal_obstacle",
            "obstacle_model": str(args.obstacle_model.expanduser().resolve()),
            "obstacle_threshold": float(obstacle_constraint.threshold),
            "obstacle_margin": float(args.obstacle_margin),
            "max_mpc_steps": int(args.max_mpc_steps),
            "goal_tolerance": goal_tolerance,
            "dataset_max_episode_steps": dataset_max_episode_steps,
            "control_decimation": control_decimation,
            "control_timestep": float(episode["control_timestep"]),
            "num_executed_steps": int(len(executed_actions_raw)),
            "success": bool(success),
            "stop_reason": stop_reason,
            "latent_goal_distance_initial": float(latent_goal_distances[0]),
            "latent_goal_distance_final": float(latent_goal_distances[-1]),
            "task_target_distance_initial": float(task_target_distances[0]),
            "task_target_distance_final": float(task_target_distances[-1]),
            "left_attachment_distance_initial": float(left_attachment_distances[0]),
            "left_attachment_distance_final": float(left_attachment_distances[-1]),
            "right_attachment_distance_initial": float(right_attachment_distances[0]),
            "right_attachment_distance_final": float(right_attachment_distances[-1]),
            "rope_length_error_initial": float(rope_length_errors[0]),
            "rope_length_error_final": float(rope_length_errors[-1]),
            "goal_task_target": goal_task_target.tolist(),
            "final_task_target": np.asarray(final_info["task_target"], dtype=np.float32).tolist(),
            "goal_left_attachment_pos": goal_left_pos.tolist(),
            "goal_right_attachment_pos": goal_right_pos.tolist(),
            "final_left_attachment_pos": np.asarray(final_info["left_attachment_pos"], dtype=np.float32).tolist(),
            "final_right_attachment_pos": np.asarray(final_info["right_attachment_pos"], dtype=np.float32).tolist(),
            "goal_rope_length": goal_rope_length.tolist(),
            "final_rope_length": np.asarray(final_info["rope_length"], dtype=np.float32).tolist(),
            "final_qpos": np.asarray(final_info["qpos"], dtype=np.float32).tolist(),
            "final_qvel": np.asarray(final_info["qvel"], dtype=np.float32).tolist(),
            "final_control": np.asarray(final_info["control"], dtype=np.float32).tolist(),
            "solve_times_ms": solve_times_ms,
            "sqp_iterations": sqp_iterations,
            "sqp_costs": sqp_costs,
            "obstacle_slacks": obstacle_slacks,
            "solver_accepted": solver_accepted,
            "latent_goal_distances": latent_goal_distances,
            "embedding_goal_distances": embedding_goal_distances,
            "task_target_distances": task_target_distances,
            "left_attachment_distances": left_attachment_distances,
            "right_attachment_distances": right_attachment_distances,
            "rope_length_errors": rope_length_errors,
            "executed_actions_raw": [action.tolist() for action in executed_actions_raw],
            "executed_actions_norm": [action.tolist() for action in executed_actions_norm],
            "dataset_start_pixel_l2": float(np.linalg.norm(start_frame.astype(np.float32) - dataset_pixels_np[0].astype(np.float32))),
            "dataset_goal_pixel_l2": float(np.linalg.norm(goal_frame.astype(np.float32) - dataset_pixels_np[-1].astype(np.float32))),
            "dataset_goal_latent_distance": float(torch.linalg.vector_norm(true_latents[-1] - goal_emb).item()),
        }

    metrics_path = out_dir / "metrics.json"
    with metrics_path.open("w", encoding="utf-8") as handle:
        json.dump(metrics, handle, indent=2)

    video_path = str(save_rollout_video(rollout_frames, out_dir, fps=args.video_fps)) if rollout_frames else None

    print(f"Saved to: {out_dir}")
    if video_path is not None:
        print(f"Video: {video_path}")
    print(f"Metrics: {metrics_path}")
    if interrupted:
        print("Interrupted by user; saved partial rollout.")


if __name__ == "__main__":
    main()
